// src/constants/goals.js
// 40by40 — Master goals config
// 38 goals across 7 categories
// Types: daily | monthly | quarterly | cumulative | milestone

export const CATEGORIES = [
  {
    id: "health",
    label: "Health & Fitness",
    emoji: "💪",
    color: "#ef4444",
    colorLight: "#fef2f2",
    colorBorder: "#fecaca",
    goals: [
      {
        id: "mobile_usage",
        dbId: 1,
        title: "Mobile usage under 4 hrs/day",
        type: "daily",
        table: "daily_logs",
        field: "mobile_mins",
        targetValue: 240,
        unit: "min",
        direction: "under",
      },
      {
        id: "social_media",
        dbId: 2,
        title: "Social media under 1 hr/day",
        type: "daily",
        table: "daily_logs",
        field: "social_mins",
        targetValue: 60,
        unit: "min",
        direction: "under",
      },
      {
        id: "walking",
        dbId: 3,
        title: "Walk at least 544 km",
        type: "cumulative",
        table: "daily_logs",
        field: "walk_km",
        targetValue: 544,
        stretchTarget: 600,
        unit: "km",
        direction: "over",
      },
      {
  id: "weight",
  dbId: 26,
  title: "Weight ~70 kg (no tummy)",
  type: "monthly",
  table: "monthly_checkins",
  field: "weight_kg",
  displayOnly: true,
},
      {
        id: "sport",
        dbId: 27,
        title: "Play sport at least twice a month",
        type: "monthly",
        table: "monthly_checkins",
        field: "played_sport",
      },
    ],
  },

  {
    id: "mind",
    label: "Mind & Learning",
    emoji: "🧠",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#ddd6fe",
    goals: [
      {
        id: "books",
        dbId: 4,
        title: "Read at least 40 books (incl. 4 Tamil)",
        type: "cumulative",
        table: "books",
        targetValue: 40,
        subTarget: { label: "Tamil books", value: 4 },
        unit: "books",
        direction: "over",
      },
      {
        id: "upskilling",
        dbId: 8,
        title: "Upskilling course at reputed institution",
        type: "milestone",
        table: "milestones",
        hasTextField: true,
        textFieldLabel: "Course name & institution",
      },
      {
        id: "kannada",
        dbId: 9,
        title: "Learn to speak Kannada",
        type: "milestone",
        table: "milestones",
        fuzzy: true,
      },
      {
        id: "cooking",
        dbId: 30,
        title: "Learn to cook Rasam and Potato",
        type: "milestone",
        table: "milestones",
        fuzzy: true,
      },
      {
        id: "chess_carrom",
        dbId: 34,
        title: "Teach Chess/Carrom to Vaibhav",
        type: "milestone",
        table: "milestones",
         fuzzy: true, 
      },
      {
        id: "tech_projects",
        dbId: 38,
        title: "3 Technology projects like this",
        type: "milestone",
        table: "milestones",
         fuzzy: true,
      },
    ],
  },

  {
    id: "career",
    label: "Career & Finance",
    emoji: "💼",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fde68a",
    goals: [
      {
        id: "articles",
        dbId: 5,
        title: "Publish at least 14 articles",
        type: "cumulative",
        table: "articles",
        targetValue: 14,
        unit: "articles",
        direction: "over",
      },
      {
        id: "pf_transfer",
        dbId: 6,
        title: "Move PF from Maruti to EPFO",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "new_job",
        dbId: 7,
        title: "Change job (on notice period)",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "savings",
        dbId: 25,
        title: "INR 40 lacs in savings",
        type: "cumulative",
        table: "monthly_checkins",
        field: "savings_inr",
        targetValue: 4000000,
        unit: "INR",
        direction: "over",
      },
      {
        id: "charity",
        dbId: 28,
        title: "Spend INR 50K on charity",
        type: "cumulative",
        table: "monthly_checkins",
        field: "charity_inr",
        targetValue: 50000,
        unit: "INR",
        direction: "over",
      },
      {
        id: "investment",
        dbId: 29,
        title: "Diversify to another investment model",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "vaibhav_savings",
        dbId: 35,
        title: "INR 1 lac in Vaibhav's account",
        type: "milestone",
        table: "milestones",
      },
    ],
  },

  {
    id: "travel",
    label: "Travel & Experiences",
    emoji: "✈️",
    color: "#06b6d4",
    colorLight: "#ecfeff",
    colorBorder: "#a5f3fc",
    goals: [
      {
        id: "first_class_train",
        dbId: 17,
        title: "One First Class train journey",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "spontaneous_trip",
        dbId: 18,
        title: "One spontaneous unplanned trip",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "unique_stay",
        dbId: 19,
        title: "Unique stay — camp or treehouse",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "karaikudi_trip",
        dbId: 20,
        title: "Karaikudi – Madurai – Srivilliputtur trip",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "foreign_trip",
        dbId: 21,
        title: "One foreign trip",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "ajanta_ellora",
        dbId: 22,
        title: "Ajanta and Ellora trip",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "honeymoon2",
        dbId: 23,
        title: "Honeymoon 2.0 with Akshaya",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "boys_trip",
        dbId: 24,
        title: "Boys trip with Praveen",
        type: "milestone",
        table: "milestones",
      },
    ],
  },

  {
    id: "relationships",
    label: "Relationships & People",
    emoji: "❤️",
    color: "#ec4899",
    colorLight: "#fdf2f8",
    colorBorder: "#fbcfe8",
    goals: [
      {
        id: "best_friends",
        dbId: 11,
        title: "Meet at least 4 of 5 best friends",
        type: "cumulative",
        table: "monthly_checkins",
        field: "friends_met",
        targetValue: 4,
        unit: "friends",
        direction: "over",
      },
      {
        id: "thankyou_notes",
        dbId: 16,
        title: "14 handwritten thank-you notes",
        type: "cumulative",
        table: "monthly_checkins",
        field: "notes_sent",
        targetValue: 14,
        unit: "notes",
        direction: "over",
      },
      {
        id: "couple_toys",
        dbId: 31,
        title: "Couple toys 😄",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "couple_massage",
        dbId: 32,
        title: "Couple massage",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "jewel_akshaya",
        dbId: 33,
        title: "One jewel for Akshaya",
        type: "milestone",
        table: "milestones",
      },
      {
  id: "family_connect",
  dbId: 37,
  title: "Connect better with family & friends",
  type: "milestone",
  table: "milestones",
  fuzzy: true,
},
    ],
  },

  {
    id: "digital",
    label: "Digital & Lifestyle",
    emoji: "📱",
    color: "#10b981",
    colorLight: "#ecfdf5",
    colorBorder: "#a7f3d0",
    goals: [
      {
        id: "zero_social_weeks",
        dbId: 12,
        title: "4 weeks of zero social media",
        type: "cumulative",
        table: "monthly_checkins",
        field: "zero_social_weeks",
        targetValue: 4,
        unit: "weeks",
        direction: "over",
      },
      {
        id: "skincare",
        dbId: 13,
        title: "Maintain skincare routine",
        type: "monthly",
        table: "monthly_checkins",
        field: "skincare_done",
      },
      {
        id: "digital_declutter",
        dbId: 15,
        title: "Declutter digital life (all aspects)",
        type: "milestone",
        table: "milestones",
      },
      {
        id: "new_tv",
        dbId: 36,
        title: "Buy new TV",
        type: "milestone",
        table: "milestones",
      },
    ],
  },

  {
    id: "legacy",
    label: "Legacy & Meaning",
    emoji: "🌳",
    color: "#84cc16",
    colorLight: "#f7fee7",
    colorBorder: "#d9f99d",
    goals: [
      {
        id: "family_tree",
        dbId: 14,
        title: "Family tree / Audio history with father",
        type: "milestone",
        table: "milestones",
      },
      // 2 more goals to be added
    ],
  },
];

// ─── Type metadata ─────────────────────────────────────────────────────────────

export const GOAL_TYPE_META = {
  daily:      { label: "Daily",      bg: "#dbeafe", text: "#1d4ed8" },
  monthly:    { label: "Monthly",    bg: "#fae8ff", text: "#a21caf" },
  quarterly:  { label: "Quarterly",  bg: "#ffedd5", text: "#c2410c" },
  cumulative: { label: "Cumulative", bg: "#dcfce7", text: "#15803d" },
  milestone:  { label: "Milestone",  bg: "#f1f5f9", text: "#475569" },
};

// ─── Helpers ───────────────────────────────────────────────────────────────────

export const ALL_GOALS = CATEGORIES.flatMap((cat) =>
  cat.goals.map((g) => ({ ...g, categoryId: cat.id, categoryLabel: cat.label }))
);

export const TOTAL_GOALS = ALL_GOALS.length; // 38 (36 defined + 2 pending)

export const BIRTHDAY = new Date("2027-05-09T00:00:00+05:30");
